version: '3.8'
services:

  db:
    image: mongo:latest
    container_name: db
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_DATABASE: post

    healthcheck:
      test: "exit 0"




